# Generated by Django 3.1.7 on 2023-02-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_auto_20210318_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='validity',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
